### ISSUE TITLE
Can @DataClassGenerate be automatically added for all data classes?

### ISSUE THREAD

**Issue by ysy950803** [facebookincubator/dataclassgenerate#17]
I have a lot of data classes in my project and adding the DataClassGenerate annotation to each one would be quite tedious. Is there a way or a MODE that could be added to automatically annotate all data classes? Thanks!

**Comment by ysy950803** [comment]
Just like:
```
mode.set(DataClassGenerateMode.AUTO) // defaults to EXPLICIT
```

**Comment by nghuiqin** [comment]
Hi @ysy950803, we do have default configuration available. Please check this:
https://github.com/facebookincubator/dataclassgenerate?tab=readme-ov-file#how-to-use-in-your-project
